version: "3.8"

services:
  app:
    build: .
    container_name: chatwoot-wpp-integration
    restart: always
    environment:
      - DATABASE_HOST=
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=
      - DATABASE_PASSWORD=
    ports:
      - "3000:3000"

  